### ISSUE TITLE
Can this be used to static scan an IPA on macOS?

### ISSUE THREAD

**Issue by stonedauwg** [Soluto/mobsf-ci#1]
Running this to scan an IPA on macOS with Docker Desktop results in an error "Static Analysis of iOS IPA requires OSX". Is this because running it in a Docker image results in MobSF running under a virtual Linux/Ubuntu and not macOS?

**Comment by omerlh** [comment]
Yep, I wonder if this is something we can solve somehow - I'm not familiar with what exactly it needs from MacOS - but maybe it's something we can expose for the docker container.

**Comment by poldenais** [comment]
Hi does anyone know if mobsf running in a ci environment will work with an iOS IPA file? Is there any workaround

**Comment by omerlh** [comment]
It needs some investigation. Worst case, you can run the same commands as the docker container, just directly on Mac.

**Comment by ebickle** [comment]
Hi there! The maintainer of this repository left the company some time ago and we archived the repository at that time. I'm closing out some old issues as part of a cleanup to our GitHub repositories.

If you're still using this solution, please migrate to an alternative as soon as possible. Thanks!
