### ISSUE TITLE
Running in Jenkins

### ISSUE THREAD

**Issue by poldenais** [Soluto/mobsf-ci#2]
Hi ,
Thanks for the repo. In terms of scripting this In Jenkins, how can I do that?

Will it run for Bothe iOS (IPA) and Android (APK) in Jenkins?

Thanks,
Pol

**Comment by omerlh** [comment]
See #1 - unfortunately, it's impossible to use that for IPAs. Regarding Android and Jenkins - all that is required is running a single docker-compose command - so I assume it should be possible to run on Jenkins, although I'm not familiar with it.

**Comment by poldenais** [comment]
Thanks I would definitely need mobsf in our pipeline to work on IPA and APK

**Comment by omerlh** [comment]
hey @poldenais can I close this issue for now?

**Comment by poldenais** [comment]
> hey @poldenais can I close this issue for now?

Thanks Omer. It can be closed.
