### ISSUE TITLE
mobsf-ci:0.3.0 not found

### ISSUE THREAD

**Issue by YuryPashkov** [Soluto/mobsf-ci#3]
I've tried to run mobsf-ci:0.3.0 with using docker app as mention here https://github.com/Soluto/mobsf-ci#docker-app and got following error

`Error: docker.io/omerl/mobsf-ci:0.3.0: failed to resolve bundle manifest "docker.io/omerl/mobsf-ci:0.3.0": docker.io/omerl/mobsf-ci:0.3.0 not found
ERROR: Top level object in 'None' needs to be an object not '<class 'NoneType'>'.`

I've use docker version 19.03.1, build 74b1e89

**Comment by omerlh** [comment]
Can you try the same command just without tag? it seems that the tag does not exist

**Comment by 0xbadshah** [comment]
Now I get the output `docker.io/omerl/mobsf-ci:latest: invalid media type "application/vnd.docker.distribution.manifest.v2+json" for bundle manifest`

**Comment by omerlh** [comment]
It's pretty old, and I don't have the time to fix the docker app build - can you try following the [guide](https://github.com/Soluto/mobsf-ci#usage) without docker app? Of course, if you have time and you want to investigate why the docker app thing is not working, a PR is welcomed :)

**Comment by ebickle** [comment]
Hi there! The maintainer of this repository left the company some time ago and we archived the repository at that time. I'm closing out some old issues as part of a cleanup to our GitHub repositories.

If you're still using this solution, please migrate to an alternative as soon as possible. Thanks!
