### ISSUE TITLE
MobSF request failed due to unknwon error No such file or directory @ rb_sysopen - 

### ISSUE THREAD

**Issue by bc-venkata** [Soluto/mobsf-ci#6]
How do I pass a file from a volume as an argument to docker-compose? 
I have this coomand `TARGET_PATH='configuration:/cfg/bcapp.apk' | docker-compose up --build --exit-code-from scan`

The target path is actually a docker volume which holds the apk file as output of the build process. I need to do this as required by circleci; https://circleci.com/docs/2.0/building-docker-images/#mounting-folders

Successfully built 8c08a5eb5d9b
Successfully tagged mobsfci_scan:latest
Creating mobsfci_mobsf_1 ... 
Creating mobsfci_mobsf_1 ... doneCreating mobsfci_scan_1  ... 
Creating mobsfci_scan_1  ... doneAttaching to mobsfci_mobsf_1, mobsfci_scan_1
mobsf_1  | [2019-11-08 00:16:29 +0000] [1] [INFO] Starting gunicorn 19.9.0
scan_1   | timeout: unrecognized option: t
mobsf_1  | [2019-11-08 00:16:29 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
mobsf_1  | [2019-11-08 00:16:29 +0000] [1] [INFO] Using worker: threads
scan_1   | BusyBox v1.30.1 (2019-06-12 17:51:55 UTC) multi-call binary.
scan_1   | 
scan_1   | Usage: timeout [-s SIG] SECS PROG ARGS
scan_1   | 
scan_1   | Runs PROG. Sends SIG to it if it is not gone in SECS seconds.
scan_1   | Default SIG: TERM.
scan_1   | wait-for-it.sh: timeout occurred after waiting 15 seconds for mobsf:8000
scan_1   | Starting to scan ""
scan_1   | MobSF request failed due to unknwon error No such file or directory @ rb_sysopen - 
mobsfci_scan_1 exited with code 1

**Comment by bc-venkata** [comment]
Could you please provide any update on this?

**Comment by omerlh** [comment]
Yes, sorry. Could you please try `TARGET_PATH='cfg/bcapp.apk'`? It should only be the path inside the docker, without the mounting config.

**Comment by 0xklaue** [comment]
Hi @omerlh - I have slightly modified `docker-compose.yml` to provide direct path to apk
```
version: '3'

services:
  mobsf:
    image: opensecurity/mobile-security-framework-mobsf:latest
    environment:
      - MOBSF_API_KEY=12345
    ports:
     - 8000:8000

  scan:
    build:
      context: ./scan
    environment:
      - MOBSF_URL=http://mobsf:8000/
      - TARGET_PATH=/home/jenkins/mobsf-ci/target/example.apk

    volumes:
      - "/home/jenkins/mobsf-ci/output:/app/output"
      - "/home/jenkins/mobsf-ci/target:/app/target"

    depends_on:
      - mobsf
```

I'm getting the following error message:

```
jenkins@jenkins-example:~/mobsf-ci$ sudo docker-compose up --build --exit-code-from scan
[sudo] password for jenkins:
WARNING: The PWD variable is not set. Defaulting to a blank string.
WARNING: using --exit-code-from implies --abort-on-container-exit
Building scan
Step 1/6 : FROM ruby:2.5-alpine
 ---> 4854dd6e8222
Step 2/6 : WORKDIR /app
 ---> Using cache
 ---> c5c5bd293a82
Step 3/6 : COPY Gemfile Gemfile.lock /app/
 ---> Using cache
 ---> f873494b26d0
Step 4/6 : RUN bundle && apk add --update bash
 ---> Using cache
 ---> af1afc606ea1
Step 5/6 : COPY . .
 ---> Using cache
 ---> c06f761a7d4b
Step 6/6 : CMD ./wait-for-it.sh mobsf:8000 -- ruby scan.rb
 ---> Using cache
 ---> 8b04cc36544c
Successfully built 8b04cc36544c
Successfully tagged mobsfci_scan:latest
Starting mobsfci_mobsf_1 ...
Starting mobsfci_mobsf_1 ... done
Recreating mobsfci_scan_1 ...
Recreating mobsfci_scan_1 ... done
Attaching to mobsfci_mobsf_1, mobsfci_scan_1
scan_1   | timeout: unrecognized option: t
scan_1   | BusyBox v1.32.1 () multi-call binary.
scan_1   |
scan_1   | Usage: timeout [-s SIG] SECS PROG ARGS
scan_1   |
scan_1   | Runs PROG. Sends SIG to it if it is not gone in SECS seconds.
scan_1   | Default SIG: TERM.
scan_1   | wait-for-it.sh: timeout occurred after waiting 15 seconds for mobsf:8000
mobsf_1  | [INFO] 06/Feb/2021 14:19:33 -
mobsf_1  |   __  __       _    ____  _____   _____  _____
mobsf_1  |  |  \/  | ___ | |__/ ___||  ___| |___ / |___ /
mobsf_1  |  | |\/| |/ _ \| '_ \___ \| |_      |_ \   |_ \
mobsf_1  |  | |  | | (_) | |_) |__) |  _|    ___) | ___) |
mobsf_1  |  |_|  |_|\___/|_.__/____/|_|     |____(_)____/
mobsf_1  |
mobsf_1  | [INFO] 06/Feb/2021 14:19:33 - Mobile Security Framework v3.3.0 Beta
mobsf_1  | [INFO] 06/Feb/2021 14:19:33 -
mobsf_1  | API Key read from environment variable
mobsf_1  | [INFO] 06/Feb/2021 14:19:33 - OS: Linux
mobsf_1  | [INFO] 06/Feb/2021 14:19:33 - Platform: Linux-4.15.0-135-generic-x86_64-with-glibc2.29
mobsf_1  | [INFO] 06/Feb/2021 14:19:33 - Dist: ubuntu 20.04 focal
mobsf_1  | [INFO] 06/Feb/2021 14:19:33 - MobSF Basic Environment Check
scan_1   | Starting to scan "/home/jenkins/mobsf-ci/target/example.apk"
scan_1   | MobSF request failed due to unknwon error No such file or directory @ rb_sysopen - /home/jenkins/mobsf-ci/target/example.apk
mobsf_1  | REST API Key: 12345
mobsf_1  | No changes detected
mobsfci_scan_1 exited with code 1
Aborting on container exit...
Stopping mobsfci_mobsf_1 ... done
jenkins@jenkins-example:~/mobsf-ci$
```

**Comment by omerlh** [comment]
Look like this is the actual error:
```
MobSF request failed due to unknwon error No such file or directory @ rb_sysopen - /home/jenkins/mobsf-ci/target/example.apk
```

Can you ensure the file exist on this path?

**Comment by 0xklaue** [comment]
Yes. I kept example.apk under the following path: /home/jenkins/mobsf-ci/target

**Comment by ebickle** [comment]
Hi there! The maintainer of this repository left the company some time ago and we archived the repository at that time. I'm closing out some old issues as part of a cleanup to our GitHub repositories.

If you're still using this solution, please migrate to an alternative as soon as possible. Thanks!
