### ISSUE TITLE
MobSF CI not working on Windows 10 system

### ISSUE THREAD

**Issue by dayasagar12** [Soluto/mobsf-ci#8]
Hi,

I have installed docker on my Windows and I am trying to use msbsf-ci, but it is showing below error. Can you please let me know if it works only on Linux platform and not on Windows

Attaching to mobsf-ci_mobsf_1, mobsf-ci_scan_1
mobsf_1  | [2020-06-02 10:41:06 +0000] [1] [INFO] Starting gunicorn 20.0.4
mobsf_1  | [2020-06-02 10:41:06 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
mobsf_1  | [2020-06-02 10:41:06 +0000] [1] [INFO] Using worker: threads
mobsf_1  | [2020-06-02 10:41:06 +0000] [7] [INFO] Booting worker with pid: 7
': No such file or directorye 'bash
mobsf-ci_scan_1 exited with code 127
Aborting on container exit...
Stopping mobsf-ci_mobsf_1 ... done

**Comment by omerlh** [comment]
I honestly not sure... I think it's because bash is missing for some reason. I did not tested it on Windows yet

**Comment by ebickle** [comment]
Hi there! The maintainer of this repository left the company some time ago and we archived the repository at that time. I'm closing out some old issues as part of a cleanup to our GitHub repositories.

If you're still using this solution, please migrate to an alternative as soon as possible. Thanks!
