### ISSUE TITLE
MobSF request failed due to unknwon error Failed to open TCP connection to mobsf:8000 v2

### ISSUE THREAD

**Issue by Na4aX** [Soluto/mobsf-ci#9]
Hi, I had the same issue than #4 but the fix #5 did not help.

With some testing I discovered that there might be a race condition between the Mobsf service and the first API call.
Adding a sleep to let the time to the Mobsf service to setup properly fixed my issue.

In scan/scan.rb :
```diff
require 'net/http'
require 'multipart_body'
require 'uri'
require 'json'

mobsf_url = ENV["MOBSF_URL"]
target = ENV["TARGET_PATH"]

+ sleep 5

puts "Starting to scan \"#{target}\""
```

The "sleep **5**" is totally arbitrary and no further test has been done since its not annoying and it works.

Hope that help.

**Comment by omerlh** [comment]
Hey! Unfortunately, I don't have time right now to look into this issue. Feel free to open a PR, I'll merge it :)

**Comment by ebickle** [comment]
Hi there! The maintainer of this repository left the company some time ago and we archived the repository at that time. I'm closing out some old issues as part of a cleanup to our GitHub repositories.

If you're still using this solution, please migrate to an alternative as soon as possible. Thanks!
